### PR TITLE
Bump `@getflywheel/local` to 8.0.0

### PR DESCRIPTION
**Pull request by kienstra**
* Bumps `@getflywheel/local` to 8.0.0
* Bumps some other NPM packages for general maintenance
* This add-on still works well with `@getflywheel/local` version `8.0.0`:

oidsbf-sdf

### Testing Steps 
Same as https://github.com/getflywheel/local-addon-image-optimizer/pull/79#issue-1914317364

### CODE REVIEW

**Comment by kienstra** [comment]
The command `yarn` fails with:

```sh
$ tsc
node_modules/@getflywheel/local/main.d.ts:915:24 - error TS2307: Cannot find module '../main/capi/client/api' or its corresponding type declarations.

915   environment?: import('../main/capi/client/api').SiteInstalls.EnvironmentEnum
                           ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

That's because there is no `main/capi/` file to import from in the [packaged](https://www.npmjs.com/package/@getflywheel/local) `getflywheel/local`:

Screenshot 2023-09-22 at 5 28 11 PM

…though there is in the source:

https://github.com/getflywheel/flywheel-local/blob/ab9a4a58947fe0a93813c7102b7278d4ec870326/app/api/main.d.ts#L915C17-L915C79

**Comment by kienstra** [comment]
I made the [tests fail](https://app.circleci.com/pipelines/github/getflywheel/local-addon-image-optimizer/111/workflows/f76c44ae-6fe7-46b7-9a90-1056dba4fdd4/jobs/1130), looking at that now.

**Review by bgturner — APPROVED** [review]
Looks good! I was able to `yarn install && npm pack` to create a `tgz` which optimized images in Local Core Beta 8.0.0!

**Comment by kienstra** [comment]
Thanks a lot, @bgturner! I'm working on fixing the unit tests.

File: package.json [hunk 1]
```diff
@@ -69,13 +69,14 @@
...
   "dependencies": {
-    "@getflywheel/local-components": "^17.6.3",
+    "@getflywheel/local-components": "^17.7.1",
     "@reduxjs/toolkit": "^1.4.0",
     "classnames": "^2.2.6",
-    "dateformat": "^3.0.3",
-    "fs-extra": "^9.0.1",
+    "dateformat": "^5.0.3",
+    "fs-extra": "^11.1.1",
+    "glob": "7.2.0",
```
Comment (kienstra) [inline package.json:77]: This is the same `glob` version that was in the `master` branch:

```sh
# yarn && yarn why glob                      
…
✨  Done in 10.84s.
✨  Done in 16.14s.
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "glob"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "glob@7.2.0"
info Reasons this module exists
   - "@getflywheel#local#awilix" depends on it
   - Hoisted from "@getflywheel#local#awilix#glob"
   - Hoisted from "jest#@jest#core#jest-config#glob"
   - Hoisted from "jest#@jest#core#@jest#reporters#glob"
   - Hoisted from "jest#@jest#core#jest-runtime#glob"
   - Hoisted from "jest#@jest#core#rimraf#glob"
   - Hoisted from "jest#@jest#core#@jest#transform#babel-plugin-istanbul#test-exclude#glob"
info Disk size without dependencies: "64KB"
info Disk size with unique dependencies: "204KB"
info Disk size with transitive dependencies: "300KB"
info Number of shared dependencies: 6
✨  Done in 0.56s.
```

Comment (kienstra) [reply package.json:77]: Hi @bgturner, is it OK to merge with https://github.com/getflywheel/local-addon-image-optimizer/pull/78/commits/d3c227fa696893f0aae597b5259aee4587ac7649?

Comment (bgturner) [reply package.json:77]: Nice! Doing some QA and the addon still seems to work. Approved!

**Review by bgturner — APPROVED** [review]
LGTM!
